### ISSUE TITLE
If the focused window is maximized and on my right monitor, `pfd` outputs my left monitor.

### ISSUE THREAD

**Issue by eepykate** [tudurom/disputils#5]
[this is my screen layout](https://i.imgur.com/36iPwSv.png) (1440x900, 1920x1080)

I am using bspwm on arch. Setting the left outer-window padding to 1px fixes it.

**Comment by tudurom** [comment]
Which one is your second monitor?

**Comment by eepykate** [comment]
HDMI-0 is primary and DVI-D-0 is the secondary.

**Comment by tudurom** [comment]
@GaugeK can you try the fix i pushed in the issue_5 branch (commit 1dcbe31)?

**Comment by eepykate** [comment]
That works!

**Comment by tudurom** [comment]
Great! It's in master now.
